# Generated by Django 5.2.7 on 2025-10-22 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 17, 53, 20, 511917, tzinfo=datetime.timezone.utc)),
        ),
    ]
